### ISSUE TITLE
Not an issue: plugin description on Volumio.org

### ISSUE THREAD

**Issue by chsims1** [ElmarJ/volumio-onedrive-plugin#1]
Hi Elmar, I've just noticed that your plugin doesn't have a description in Volumio Plugins https://volumio.org/forum/volumio-plugins-collection-t6251.html

Would you mind adding a post so that I can include your plugin in the list?

Cheers.

**Comment by ElmarJ** [comment]
Hi Ian, sorry for my late response and thanks for letting me know. I don't know if it was added by someone else in the meantime, but it is mentioned now (under "Miscellanea"). Moreover, it is now also available within the list of plugins from within Volumio itself.
